SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RESTAURANT](
	[ID] [int] NOT NULL IDENTITY,
	[SOCIAL_NAME] [varchar](150) NOT NULL,
	[FANTASY_NAME] [varchar](150) NULL,
	[CATEGORY] [varchar](50) NULL,
	[DELIVERY_ESTIMATE] [int] NOT NULL,
	[RATING] [float] NULL,
	[IMAGE_PATH] [varchar](150) NULL,
	[ABOUT] [varchar](500) NULL,
	[FUNCTIONAL_HOURS] [varchar](150) NULL,
 CONSTRAINT [PK_RESTAURANT] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAYMENT_OPTION](
	[ID] [int] NOT NULL IDENTITY,
	[NAME] [varchar](70) NOT NULL,
 CONSTRAINT [PK_PAYMENT_OPTION] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE Restaurants
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PERMISSION](
	[ID] [int] NOT NULL IDENTITY,
	[PERMISSION] [varchar](150) NULL,
 CONSTRAINT [PK_PERMISSION] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CUSTOMER](
	[ID] [int] NOT NULL IDENTITY,
	[NAME] [varchar](150) NULL,
	[EMAIL] [varchar](150) NOT NULL,
	[TELEPHONE] [varchar](30) NOT NULL,
	[ADRESS] [varchar](200) NOT NULL,
	[NUMBER] [varchar](30) NOT NULL,
	[OPTIONAL_ADRESS] [varchar](100) NULL,
	[ACCESS_KEY] [varchar](32) NOT NULL,
	[IMAGE_PATH] [varchar](150) NULL,
	[ID_PERMISSION] [int] NOT NULL,
 CONSTRAINT [PK_CUSTOMER] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUSTOMER]  WITH CHECK ADD  CONSTRAINT [FK_CUSTOMER_PERMISSION] FOREIGN KEY([ID_PERMISSION])
REFERENCES [dbo].[PERMISSION] ([ID])
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REVIEW](
	[ID] [int] NOT NULL IDENTITY,
	[USER_NAME] [varchar](150) NULL,
	[DATE_REVIEW] [datetime] NULL,
	[RATING] [float] NULL,
	[COMMENTS] [varchar](500) NULL,
	[ID_RESTAURANT] [int] NOT NULL,
 CONSTRAINT [PK_REVIEW] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REVIEW]  WITH CHECK ADD  CONSTRAINT [FK_REVIEW_RESTAURANT] FOREIGN KEY([ID_RESTAURANT])
REFERENCES [dbo].[RESTAURANT] ([ID])
GO
ALTER TABLE [dbo].[REVIEW] CHECK CONSTRAINT [FK_REVIEW_RESTAURANT]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MENU](
	[ID] [int] NOT NULL IDENTITY,
	[IMAGE_PATH] [varchar](150) NULL,
	[PRODUCT_NAME] [varchar](150) NOT NULL,
	[DESCRIPTION] [varchar](250) NULL,
	[PRICE] [decimal](18, 0) NOT NULL,
	[ID_RESTAURANT] [int] NOT NULL,
 CONSTRAINT [PK_MENU] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MENU]  WITH CHECK ADD  CONSTRAINT [FK_MENU_RESTAURANT] FOREIGN KEY([ID_RESTAURANT])
REFERENCES [dbo].[RESTAURANT] ([ID])
GO
ALTER TABLE [dbo].[MENU] CHECK CONSTRAINT [FK_MENU_RESTAURANT]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDER](
	[ID] [int] NOT NULL IDENTITY,
	[EMAIL] [varchar](150) NOT NULL,
	[TELEPHONE] [varchar](30) NOT NULL,
	[ADRESS] [varchar](200) NOT NULL,
	[NUMBER] [varchar](30) NOT NULL,
	[OPTIONAL_ADRESS] [varchar](100) NULL,
	[ID_PAYMENT_OPTION] [int] NOT NULL,
	[ID_USER] [int] NOT NULL,
 CONSTRAINT [PK_ORDER] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDER]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_PAYMENT_OPTION] FOREIGN KEY([ID_PAYMENT_OPTION])
REFERENCES [dbo].[PAYMENT_OPTION] ([ID])
GO
ALTER TABLE [dbo].[ORDER] CHECK CONSTRAINT [FK_ORDER_PAYMENT_OPTION]
GO
ALTER TABLE [dbo].[ORDER]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_CUSTOMER] FOREIGN KEY([ID_USER])
REFERENCES [dbo].[CUSTOMER] ([ID])
GO
ALTER TABLE [dbo].[ORDER] CHECK CONSTRAINT [FK_ORDER_CUSTOMER]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDER_ITEM](
	[ID] [int] NOT NULL IDENTITY,
	[QUANTITY] [int] NOT NULL,
	[PRICE] [decimal](18, 0) NOT NULL,
	[ID_PRODUTO] [int] NOT NULL,
	[ID_ORDER] [int] NOT NULL,
 CONSTRAINT [PK_ORDER_ITEM] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDER_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_ITEM_MENU] FOREIGN KEY([ID_PRODUTO])
REFERENCES [dbo].[MENU] ([ID])
GO
ALTER TABLE [dbo].[ORDER_ITEM] CHECK CONSTRAINT [FK_ORDER_ITEM_MENU]
GO
ALTER TABLE [dbo].[ORDER_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_ITEM_ORDER] FOREIGN KEY([ID_ORDER])
REFERENCES [dbo].[ORDER] ([ID])
GO
ALTER TABLE [dbo].[ORDER_ITEM] CHECK CONSTRAINT [FK_ORDER_ITEM_ORDER]
GO
