SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RESTAURANT](
	[ID] [int] NOT NULL IDENTITY,
	[SOCIAL_NAME] [varchar](150) NOT NULL,
	[FANTASY_NAME] [varchar](150) NULL,
	[CATEGORY] [varchar](50) NULL,
	[DELIVERY_ESTIMATE] [int] NOT NULL,
	[RATING] [float] NULL,
	[IMAGE_PATH] [varchar](150) NULL,
	[ABOUT] [varchar](500) NULL,
	[FUNCTIONAL_HOURS] [varchar](150) NULL,
 CONSTRAINT [PK_RESTAURANT] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
