SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REVIEW](
	[ID] [int] NOT NULL IDENTITY,
	[USER_NAME] [varchar](150) NULL,
	[DATE_REVIEW] [datetime] NULL,
	[RATING] [float] NULL,
	[COMMENTS] [varchar](500) NULL,
	[ID_RESTAURANT] [int] NOT NULL,
 CONSTRAINT [PK_REVIEW] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REVIEW]  WITH CHECK ADD  CONSTRAINT [FK_REVIEW_RESTAURANT] FOREIGN KEY([ID_RESTAURANT])
REFERENCES [dbo].[RESTAURANT] ([ID])
GO
ALTER TABLE [dbo].[REVIEW] CHECK CONSTRAINT [FK_REVIEW_RESTAURANT]
GO
