SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MENU](
	[ID] [int] NOT NULL IDENTITY,
	[IMAGE_PATH] [varchar](150) NULL,
	[PRODUCT_NAME] [varchar](150) NOT NULL,
	[DESCRIPTION] [varchar](250) NULL,
	[PRICE] [decimal](18, 0) NOT NULL,
	[ID_RESTAURANT] [int] NOT NULL,
 CONSTRAINT [PK_MENU] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MENU]  WITH CHECK ADD  CONSTRAINT [FK_MENU_RESTAURANT] FOREIGN KEY([ID_RESTAURANT])
REFERENCES [dbo].[RESTAURANT] ([ID])
GO
ALTER TABLE [dbo].[MENU] CHECK CONSTRAINT [FK_MENU_RESTAURANT]
GO
