SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDER](
	[ID] [int] NOT NULL IDENTITY,
	[EMAIL] [varchar](150) NOT NULL,
	[TELEPHONE] [varchar](30) NOT NULL,
	[ADRESS] [varchar](200) NOT NULL,
	[NUMBER] [varchar](30) NOT NULL,
	[OPTIONAL_ADRESS] [varchar](100) NULL,
	[ID_PAYMENT_OPTION] [int] NOT NULL,
	[ID_USER] [int] NOT NULL,
 CONSTRAINT [PK_ORDER] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDER]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_PAYMENT_OPTION] FOREIGN KEY([ID_PAYMENT_OPTION])
REFERENCES [dbo].[PAYMENT_OPTION] ([ID])
GO
ALTER TABLE [dbo].[ORDER] CHECK CONSTRAINT [FK_ORDER_PAYMENT_OPTION]
GO
ALTER TABLE [dbo].[ORDER]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_CUSTOMER] FOREIGN KEY([ID_USER])
REFERENCES [dbo].[CUSTOMER] ([ID])
GO
ALTER TABLE [dbo].[ORDER] CHECK CONSTRAINT [FK_ORDER_CUSTOMER]
GO